spring:
    application:
        name:   auction-service
    datasource:
        url: jdbc:postgresql://localhost:5432/auction_service
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
          ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            '[format_sql]': true
            dialect: org.hibernate.dialect.PostgreSQLDialect

    kafka:
        bootstrap-servers: localhost:9092 # Kafka broker connection URL

        consumer:
            group-id: auction-service-group # Consumer group name for partition assignment & offset tracking
            auto-offset-reset: earliest # Reads from offset 0 if no prior commit offset exists (never misses payment events)
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # Converts key bytes to String
            value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer # Converts JSON payload bytes to Java DTO
            enable-auto-commit: false # Disables auto-commit so offsets are committed manually AFTER database updates succeed

            properties:
                spring.json.trusted.packages: "*" # Allows JSON deserialization across different package names

        listener:
            ack-mode: manual # Requires explicit ack.acknowledge() call in code after DB transaction commits
          
server:
    servlet:
        context-path: /api/v1
    port: 8082
        
jwt:
  secretKey: 243567575revfvfvgrvvenveivrfhuhruvbnrevienvv